### ISSUE TITLE
Doesn't produce correct password when using chefspec & test-kitchen

### ISSUE THREAD

**Issue by StaymanHou** [sous-chefs/chef-percona#200]
I stub the EncryptedDataBagItem class, but it doesn't produce the correct password. Instead, it renders a random password
my chefspec file

```
require 'spec_helper'

describe 'uv_percona::default' do
  let(:chef_run) do
    ChefSpec::Runner.new do |node|
      node.set['percona']['skip_passwords'] = false
      node.set['percona']['cluster']['wsrep_cluster_name'] = 'percona-test-kitchen-cluster'
      node.set['percona']['cluster']['cluster_ips'] = []
    end.converge(described_recipe)
  end

  before do
    stub_command("test -f /var/lib/mysql/mysql/user.frm").and_return(true)
    stub_command("test -f /etc/mysql/grants.sql").and_return(true)
    Chef::EncryptedDataBagItem.stub(:load).and_return({
      'root' => '12345678',
      'backup' => '87654321'
    })
    Chef::EncryptedDataBagItem.stub(:load_secret).and_return(nil)
  end

  it 'installs the percona-xtradb-cluster-56 package' do
    expect(chef_run).to install_package('percona-xtradb-cluster-56')
  end

  it 'runs percona::access_grants recipe' do
    expect(chef_run).to include_recipe('percona::access_grants')
  end

  it 'renders file `/etc/mysql/grants.sql` with correct passwords' do
    expect(chef_run).to render_file('/etc/mysql/grants.sql').with_content(/root.+12345678/)
    expect(chef_run).to render_file('/etc/mysql/grants.sql').with_content(/backup.+87654321/)
  end
end
```

I provide the encrytped data bag and encrypted data bag secret file by following the steps described [here](http://atomic-penguin.github.io/blog/2013/06/07/HOWTO-test-kitchen-and-encrypted-data-bags/)
Again, it renders a random password.
my .kitchen.yml

```

---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: percona-server-1-ubuntu-12.04
    run_list:
      - recipe[uv_percona::default]
    data_bags_path: "test/integration/uv_percona/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/uv_percona/encrypted_data_bag_secret"
    attributes:
      private_ipaddress: "192.168.33.51"
      percona:
        skip_passwords: false
        cluster:
          wsrep_cluster_name: 'percona-test-kitchen-cluster'
          cluster_ips: []
    driver:
      box: ubuntu-12.04
      box_url: https://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-i386-vagrant-disk1.box
      network:
      - ["private_network", {ip: "192.168.33.51"}]
      customize:
        memory: 1024

suites:
  - name: uv_percona
    run_list:
    attributes:

```
